"""Generate / verify the baked Teleport policy verification key.

The dev policy root's PUBLIC half is vendored at keys/dev-policy-root.pub.pem
(canonical private key lives in the fairyland repo:
products/teleport/device-manager/keys/dev-policy-root.pem). The patch
patches/components/policy/core/common/cloud/cloud_policy_constants.cc.patch
bakes it as kDevPolicyKey + kPolicyVerificationKeyHash. This script is the
single generator/verifier for that content:

  uv run python scripts/gen_policy_verification_key.py           # print C snippet
  uv run python scripts/gen_policy_verification_key.py --check   # verify patch == key

Hash derivation: "1:" + first 8 bytes of SHA-256(DER SPKI), lowercase hex.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PUB_PEM = REPO / "keys" / "dev-policy-root.pub.pem"
PATCH = (
    REPO
    / "patches/components/policy/core/common/cloud/cloud_policy_constants.cc.patch"
)


def load_pub_der(pem_path: Path = PUB_PEM) -> bytes:
    m = re.search(
        r"-----BEGIN PUBLIC KEY-----(.*?)-----END PUBLIC KEY-----",
        pem_path.read_text(),
        re.S,
    )
    if not m:
        raise SystemExit(f"no PUBLIC KEY block in {pem_path}")
    return base64.b64decode("".join(m.group(1).split()))


def key_hash(der: bytes) -> str:
    return "1:" + hashlib.sha256(der).digest()[:8].hex()


def c_array_lines(der: bytes) -> str:
    """Format DER bytes in the patch's style: 12 bytes/line, 4-space indent,
    closing `};` glued to the last byte."""
    hexes = [f"0x{b:02x}" for b in der]
    lines = [
        "    " + ", ".join(hexes[i : i + 12]) + ","
        for i in range(0, len(hexes), 12)
    ]
    lines[-1] = lines[-1].rstrip(",") + "};"
    return "\n".join(lines)


def patch_dev_key(patch_path: Path = PATCH) -> tuple[bytes, str]:
    """Extract (kDevPolicyKey bytes, its kPolicyVerificationKeyHash) from the
    patch text. Tolerant of diff `+` prefixes: matches byte tokens only."""
    text = patch_path.read_text()
    m = re.search(r"kDevPolicyKey\[\] = \{(.*?)\};", text, re.S)
    if not m:
        raise SystemExit(f"kDevPolicyKey block not found in {patch_path}")
    der = bytes(int(t, 16) for t in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1)))
    hm = re.search(r'kPolicyVerificationKeyHash\[\] = "([^"]+)"', text[m.end():])
    if not hm:
        raise SystemExit(f"dev kPolicyVerificationKeyHash not found in {patch_path}")
    return der, hm.group(1)


def run_check() -> None:
    der = load_pub_der()
    patch_der, patch_hash = patch_dev_key()
    problems = []
    if patch_der != der:
        problems.append(
            f"kDevPolicyKey bytes ({len(patch_der)}) != vendored key DER ({len(der)})"
        )
    if patch_hash != key_hash(der):
        problems.append(
            f"kPolicyVerificationKeyHash {patch_hash!r} != derived {key_hash(der)!r}"
        )
    if problems:
        raise SystemExit(
            "policy verification key drift between keys/dev-policy-root.pub.pem "
            "and cloud_policy_constants.cc.patch:\n  - "
            + "\n  - ".join(problems)
            + "\nRegenerate the patch content with scripts/gen_policy_verification_key.py."
        )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify patch matches key")
    args = ap.parse_args()
    if args.check:
        run_check()
        print("policy verification key: patch matches vendored key")
        return
    der = load_pub_der()
    print("// generated by scripts/gen_policy_verification_key.py")
    print("const uint8_t kDevPolicyKey[] = {")
    print(c_array_lines(der))
    print(f'const char kPolicyVerificationKeyHash[] = "{key_hash(der)}";')


if __name__ == "__main__":
    main()
