"""Generate version artifacts into the chromium checkout from repo version files.

- chrome/VERSION  <- TELEPORT_VERSION (4-segment product version): makes every
  build-time version derivative (framework Versions/ dir, all bundle plists,
  CHROME_VERSION_STRING) the PRODUCT version.
- components/version_info/teleport_engine_version.h  <- CHROMIUM_VERSION: the
  pinned upstream engine version, consumed ONLY by the UA / UA-CH patches.

Writes are content-compared and skipped when unchanged: chrome/VERSION is an
input of nearly every target, so a gratuitous mtime bump would trigger a full
rebuild on each apply_patches run.
"""
from __future__ import annotations

import re
from pathlib import Path

from _lib import chromium_src, repo_root

_FOUR_SEG_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)\.(\d+)$")

_CHROME_VERSION_REL = Path("chrome") / "VERSION"
_ENGINE_HEADER_REL = (
    Path("components") / "version_info" / "teleport_engine_version.h")


def parse_product_version(text: str) -> tuple[int, int, int, int]:
    """Parse the 4-segment TELEPORT_VERSION. Raises ValueError on anything else
    (including legacy 3-segment values: the file must be migrated, not guessed)."""
    m = _FOUR_SEG_RE.match(text.strip())
    if not m:
        raise ValueError(
            f"TELEPORT_VERSION must be 4-segment MAJOR.MINOR.BUILD.PATCH, got {text!r}")
    return (int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4)))


def chrome_version_content(v: tuple[int, int, int, int]) -> str:
    major, minor, build, patch = v
    return f"MAJOR={major}\nMINOR={minor}\nBUILD={build}\nPATCH={patch}\n"


def parse_engine_version(text: str) -> str:
    """Validate CHROMIUM_VERSION as a 4-segment dotted string; return it stripped."""
    s = text.strip()
    if not _FOUR_SEG_RE.match(s):
        raise ValueError(f"CHROMIUM_VERSION must be 4-segment, got {text!r}")
    return s


def engine_header_content(engine_version: str) -> str:
    major = engine_version.split(".")[0]
    return (
        "// Generated by scripts/generate_version.py from CHROMIUM_VERSION.\n"
        "// Pinned upstream engine version: consumed ONLY by the UA / UA-CH\n"
        "// surface (web compat). Product versioning lives in chrome/VERSION.\n"
        "#ifndef COMPONENTS_VERSION_INFO_TELEPORT_ENGINE_VERSION_H_\n"
        "#define COMPONENTS_VERSION_INFO_TELEPORT_ENGINE_VERSION_H_\n"
        f'#define TELEPORT_ENGINE_VERSION_STRING "{engine_version}"\n'
        f'#define TELEPORT_ENGINE_VERSION_MAJOR "{major}"\n'
        "#endif  // COMPONENTS_VERSION_INFO_TELEPORT_ENGINE_VERSION_H_\n"
    )


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def write_chrome_version(root: Path | None = None) -> bool:
    root = root or repo_root()
    v = parse_product_version((root / "TELEPORT_VERSION").read_text())
    return _write_if_changed(
        chromium_src(root) / _CHROME_VERSION_REL, chrome_version_content(v))


def write_engine_header(root: Path | None = None) -> bool:
    root = root or repo_root()
    engine = parse_engine_version((root / "CHROMIUM_VERSION").read_text())
    return _write_if_changed(
        chromium_src(root) / _ENGINE_HEADER_REL, engine_header_content(engine))
